version: '3.8'
services:
  auth-service:
    image: ${DOCKER_REGISTRY:-local}/auth-service:latest
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__WebAppDatabase=Host=backend-app-db;Port=5432;Database=webapp_db;Username=admin;Password=password
      - JwtConfiguration__Key=SecretKey00000000000000000000000
      - JwtConfiguration__Issuer=auth-service
      - JwtConfiguration__Audience=webapp
      - JwtConfiguration__ExpiryMinutes=60
    ports:
      - "8080:80"
    networks:
      - app-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  db-service:
    image: ${DOCKER_REGISTRY:-local}/db-service:latest
    build:
      context: ./db-service
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__WebAppDatabase=Host=backend-app-db;Port=5432;Database=webapp_db;Username=admin;Password=password
    ports:
      - "8081:80"
    networks:
      - app-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  business-service:
    image: ${DOCKER_REGISTRY:-local}/business-service:latest
    build:
      context: ./business-service
      dockerfile: Dockerfile
    environment:
      - DbServiceUrl=http://db-service:80
    ports:
      - "8082:80"
    networks:
      - app-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  backend-app-db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webapp_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  kong:
    image: kong:3.9.0
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    configs:
      - source: kong-config
        target: /usr/local/kong/declarative/kong.yml
    networks:
      - app-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - portainer-data:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - app-net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8002:80"
    volumes:
      - pgadmin-vol:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/.pgpass:/pgpass
    networks:
      - app-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  postgres-data:
  portainer-data:
  pgadmin-vol:

configs:
  kong-config:
    file: ./kong/kong.yml

networks:
  app-net:
    driver: overlay